[package]
name = "time-tracking-parser"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.0"
strip-prefix-suffix-sane = "0.1.0"
nutype = { version = "0.6.2", features = ["serde"] }
